name: Deploy Docker to EC2
on:
  push:
    branches:
      - test
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: docker setup buildx  
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.POLLAPP_USERNAME }} # docker username
          password: ${{ secrets.POLLAPP_PASSWORD }} # docker pwd personal access token
      - name: Docker build and push docker image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          # file: ./Dockerfile
          push: true
          tags: manthad/postgress_pollappdb:v3 # docker repo name
      - name: Docker build and push docker image
        uses: docker/build-push-action@v6
        # with:
        #   platforms: linux/amd64
        #   context: .
        #   file: Dockerfile
        #   push: true
        #   tags: manthad/djangoapp-demo:v3
            
  deploy:
    runs-on: ubuntu-latest # or your self-hosted runner
    needs: build-and-push
  
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: 
            sudo docker stop postgress-container || true
            sudo docker rm -f postgress-container || true
            sudo docker container prune -f
            sudo docker rmi manthad/postgress_pollappdb:v2 || true
            sudo docker pull manthad/postgress_pollappdb:v3


            sudo docker run -d --name postgress-container -p 8001:8000 --add-host=docker.internal:host-gateway manthad/postgress_pollappdb:v3
            # -v /home/ubuntu/pollrestore/polldb_backup.sqlite3:/usr/src/app/db.sqlite3 manthad/postgress_pollappdb:v1


            # sudo docker stop fastapi_container || true
            # sudo docker rm fastapi_container || true
            # sudo docker rmi manthad/fastapi-demo:latest || true
            # sudo docker pull manthad/fastapi-demo:latest
            # sudo docker run -d --name ec2-fastapi-container -p 8000:8000 manthad/fastapi-demo:latest